task: detection

evaluator: 
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 11
remap_mscoco_category: False

train_dataloader: 
  type: DataLoader
  dataset:  
    type: VisdroneVIDDetection
    root_dir: ../dataset/VisDrone/VisDrone2019-VID-train/sequences/
    ann_dir: ../dataset/VisDrone/VisDrone2019-VID-train/annotations/
    image_set: train
    transforms: 
      type: Compose
      ops: ~
  shuffle: True
  num_workers:  4
  drop_last:  True 
  collate_fn: 
    type: BatchImageCollateFuncion

val_dataloader:
  type: DataLoader
  dataset:   
    type: VisdroneVIDDetection
    root_dir: ../dataset/VisDrone/VisDrone2019-VID-val/sequences/
    ann_dir: ../dataset/VisDrone/VisDrone2019-VID-val/annotations/
    image_set: val
    transforms:
      type: Compose
      ops:  ~ 
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type:  BatchImageCollateFuncion