__include__:  [
  '../dataset/visdrone_vid_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]

tuning:  ./rtdetrv2_r50vd_6x_coco.pth

output_dir: ./output/rtdetrv2_r50vd_visdrone

num_classes: 11

epoches: 40
use_focal_loss: True

LRScheduler:
  type:  MultiStepLR
  milestones: [12, 17]
  gamma: 0.1

LRWarmup: 
  type: LinearWarmup
  warmup_duration: 2

PResNet:
  depth: 50
  variant: d
  freeze_at: 4
  return_idx: [1, 2, 3]
  num_stages: 4
  freeze_norm: True
  pretrained: False

RTDETRPostProcessor:
  num_top_queries: 300